import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

const webSrc = (...segments: string[]) => path.resolve(import.meta.dirname, "apps/web/src", ...segments);

export default defineConfig({
  server: { host: "::", port: 8080 },
  plugins: [react()],
  resolve: {
    alias: [
      { find: "@/components/admin", replacement: webSrc("modules/admin/components") },
      { find: "@/components/billing", replacement: webSrc("modules/billing/components") },
      { find: "@/components/calendar", replacement: webSrc("modules/schedule/calendar") },
      { find: "@/components/communications", replacement: webSrc("modules/communications/components") },
      { find: "@/components/customers", replacement: webSrc("modules/customers/components") },
      { find: "@/components/dashboard", replacement: webSrc("app/components") },
      { find: "@/components/jobs", replacement: webSrc("modules/jobs/components") },
      { find: "@/components/layout", replacement: webSrc("shared/layout") },
      { find: "@/components/leads", replacement: webSrc("modules/leads/components") },
      { find: "@/components/payroll", replacement: webSrc("modules/payroll/components") },
      { find: "@/components/providers", replacement: webSrc("shared/providers") },
      { find: "@/components/reports", replacement: webSrc("modules/reports/components") },
      { find: "@/components/schedule", replacement: webSrc("modules/schedule/components") },
      { find: "@/components/settings", replacement: webSrc("modules/settings/components") },
      { find: "@/components/shared", replacement: webSrc("shared/components") },
      { find: "@/components/support", replacement: webSrc("modules/support/components") },
      { find: "@/components/transactions", replacement: webSrc("modules/transactions/components") },
      { find: "@/components/ui", replacement: webSrc("shared/ui") },
      { find: "@/hooks/use-toast", replacement: webSrc("shared/hooks/use-toast.ts") },
      { find: "@/hooks/useAddressAutocomplete", replacement: webSrc("modules/customers/hooks/useAddressAutocomplete.ts") },
      { find: "@/hooks/useAutomationConfigs", replacement: webSrc("modules/settings/hooks/useAutomationConfigs.ts") },
      { find: "@/hooks/useCompanyLanguage", replacement: webSrc("modules/settings/hooks/useCompanyLanguage.ts") },
      { find: "@/hooks/useCompanySettings", replacement: webSrc("modules/settings/hooks/useCompanySettings.ts") },
      { find: "@/hooks/useConversations", replacement: webSrc("modules/communications/hooks/useConversations.ts") },
      { find: "@/hooks/useCustomerRelationships", replacement: webSrc("modules/customers/hooks/useCustomerRelationships.ts") },
      { find: "@/hooks/useCustomerTerms", replacement: webSrc("modules/customers/hooks/useCustomerTerms.ts") },
      { find: "@/hooks/useCustomers", replacement: webSrc("modules/customers/hooks/useCustomers.ts") },
      { find: "@/hooks/useGoogle", replacement: webSrc("modules/settings/hooks/useGoogle.ts") },
      { find: "@/hooks/useGoogleCalendarSync", replacement: webSrc("modules/settings/hooks/useGoogleCalendarSync.ts") },
      { find: "@/hooks/useInvoices", replacement: webSrc("modules/billing/hooks/useInvoices.ts") },
      { find: "@/hooks/useJobGpsAlerts", replacement: webSrc("modules/jobs/hooks/useJobGpsAlerts.ts") },
      { find: "@/hooks/useJobStatusTracking", replacement: webSrc("modules/jobs/hooks/useJobStatusTracking.ts") },
      { find: "@/hooks/useJobs", replacement: webSrc("modules/jobs/hooks/useJobs.ts") },
      { find: "@/hooks/useLeads", replacement: webSrc("modules/leads/hooks/useLeads.ts") },
      { find: "@/hooks/useNotificationSound", replacement: webSrc("modules/communications/hooks/useNotificationSound.ts") },
      { find: "@/hooks/usePayrollRecords", replacement: webSrc("modules/payroll/hooks/usePayrollRecords.ts") },
      { find: "@/hooks/usePayrollRules", replacement: webSrc("modules/payroll/hooks/usePayrollRules.ts") },
      { find: "@/hooks/usePermission", replacement: webSrc("modules/auth/hooks/usePermission.ts") },
      { find: "@/hooks/usePlatformAdmin", replacement: webSrc("modules/admin/hooks/usePlatformAdmin.ts") },
      { find: "@/hooks/useQuickBooks", replacement: webSrc("modules/billing/hooks/useQuickBooks.ts") },
      { find: "@/hooks/useQuickBooksSync", replacement: webSrc("modules/billing/hooks/useQuickBooksSync.ts") },
      { find: "@/hooks/useRingCentral", replacement: webSrc("modules/communications/hooks/useRingCentral.ts") },
      { find: "@/hooks/useRingCentralSync", replacement: webSrc("modules/communications/hooks/useRingCentralSync.ts") },
      { find: "@/hooks/useSendEmail", replacement: webSrc("modules/communications/hooks/useSendEmail.ts") },
      { find: "@/hooks/useSendNotificationSMS", replacement: webSrc("modules/communications/hooks/useSendNotificationSMS.ts") },
      { find: "@/hooks/useStaff", replacement: webSrc("modules/settings/hooks/useStaff.ts") },
      { find: "@/hooks/useSupportTickets", replacement: webSrc("modules/support/hooks/useSupportTickets.ts") },
      { find: "@/hooks/useTransactionRules", replacement: webSrc("modules/transactions/hooks/useTransactionRules.ts") },
      { find: "@/hooks/useTransactions", replacement: webSrc("modules/transactions/hooks/useTransactions.ts") },
      { find: "@/contexts", replacement: webSrc("shared/contexts") },
      { find: "@/integrations", replacement: webSrc("shared/integrations") },
      { find: "@/lib", replacement: webSrc("shared/lib") },
      { find: "@/stores", replacement: webSrc("shared/stores") },
      { find: "@", replacement: webSrc() },
    ],
  },
});
