import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "path";

const webSrc = (...segments: string[]) => path.resolve(import.meta.dirname, "apps/web/src", ...segments);

export default defineConfig({
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [react()],
  resolve: {
    alias: [
      { find: "@/components/admin", replacement: webSrc("modules/admin/components") },
      { find: "@/components/auth", replacement: webSrc("modules/auth") },
      { find: "@/components/billing", replacement: webSrc("modules/billing/components") },
      { find: "@/components/calendar", replacement: webSrc("modules/schedule/calendar") },
      { find: "@/components/communications", replacement: webSrc("modules/communications/components") },
      { find: "@/components/customers", replacement: webSrc("modules/customers/components") },
      { find: "@/components/dashboard", replacement: webSrc("app/components") },
      { find: "@/components/jobs", replacement: webSrc("modules/jobs/components") },
      { find: "@/components/layout", replacement: webSrc("shared/layout") },
      { find: "@/components/leads", replacement: webSrc("modules/leads/components") },
      { find: "@/components/payroll", replacement: webSrc("modules/payroll/components") },
      { find: "@/components/providers", replacement: webSrc("shared/providers") },
      { find: "@/components/reports", replacement: webSrc("modules/reports/components") },
      { find: "@/components/schedule", replacement: webSrc("modules/schedule/components") },
      { find: "@/components/settings", replacement: webSrc("modules/settings/components") },
      { find: "@/components/shared", replacement: webSrc("shared/components") },
      { find: "@/components/support", replacement: webSrc("modules/support/components") },
      { find: "@/components/transactions", replacement: webSrc("modules/transactions/components") },
      { find: "@/components/ui", replacement: webSrc("shared/ui") },
      { find: "@/pages/admin", replacement: webSrc("modules/admin/pages") },
      { find: "@/pages/Auth", replacement: webSrc("modules/auth/AuthPage") },
      { find: "@/pages/Billing", replacement: webSrc("modules/billing/BillingPage") },
      { find: "@/pages/Communications", replacement: webSrc("modules/communications/CommunicationsPage") },
      { find: "@/pages/Customers", replacement: webSrc("modules/customers/CustomersPage") },
      { find: "@/pages/Dashboard", replacement: webSrc("app/Dashboard") },
      { find: "@/pages/GoogleCallback", replacement: webSrc("modules/settings/GoogleCallbackPage") },
      { find: "@/pages/Leads", replacement: webSrc("modules/leads/LeadsPage") },
      { find: "@/pages/NotFound", replacement: webSrc("app/NotFoundPage") },
      { find: "@/pages/Payroll", replacement: webSrc("modules/payroll/PayrollPage") },
      { find: "@/pages/Reports", replacement: webSrc("modules/reports/ReportsPage") },
      { find: "@/pages/RingCentralCallback", replacement: webSrc("modules/communications/RingCentralCallbackPage") },
      { find: "@/pages/Rules", replacement: webSrc("modules/transactions/RulesPage") },
      { find: "@/pages/Schedule", replacement: webSrc("modules/schedule/SchedulePage") },
      { find: "@/pages/SetPassword", replacement: webSrc("modules/auth/SetPasswordPage") },
      { find: "@/pages/Settings", replacement: webSrc("modules/settings/SettingsPage") },
      { find: "@/pages/Setup", replacement: webSrc("modules/auth/SetupPage") },
      { find: "@/pages/Support", replacement: webSrc("modules/support/SupportPage") },
      { find: "@/pages/SyncLogs", replacement: webSrc("modules/settings/SyncLogsPage") },
      { find: "@/pages/Transactions", replacement: webSrc("modules/transactions/TransactionsPage") },
      { find: "@/hooks/useAddressAutocomplete", replacement: webSrc("modules/customers/hooks/useAddressAutocomplete") },
      { find: "@/hooks/useAutomationConfigs", replacement: webSrc("modules/settings/hooks/useAutomationConfigs") },
      { find: "@/hooks/useCompanyLanguage", replacement: webSrc("modules/settings/hooks/useCompanyLanguage") },
      { find: "@/hooks/useCompanySettings", replacement: webSrc("modules/settings/hooks/useCompanySettings") },
      { find: "@/hooks/useConversations", replacement: webSrc("modules/communications/hooks/useConversations") },
      { find: "@/hooks/useCustomerRelationships", replacement: webSrc("modules/customers/hooks/useCustomerRelationships") },
      { find: "@/hooks/useCustomerTerms", replacement: webSrc("modules/customers/hooks/useCustomerTerms") },
      { find: "@/hooks/useCustomers", replacement: webSrc("modules/customers/hooks/useCustomers") },
      { find: "@/hooks/useGoogle", replacement: webSrc("modules/settings/hooks/useGoogle") },
      { find: "@/hooks/useGoogleCalendarSync", replacement: webSrc("modules/settings/hooks/useGoogleCalendarSync") },
      { find: "@/hooks/useInvoices", replacement: webSrc("modules/billing/hooks/useInvoices") },
      { find: "@/hooks/useJobGpsAlerts", replacement: webSrc("modules/jobs/hooks/useJobGpsAlerts") },
      { find: "@/hooks/useJobStatusTracking", replacement: webSrc("modules/jobs/hooks/useJobStatusTracking") },
      { find: "@/hooks/useJobs", replacement: webSrc("modules/jobs/hooks/useJobs") },
      { find: "@/hooks/useLeads", replacement: webSrc("modules/leads/hooks/useLeads") },
      { find: "@/hooks/useNotificationSound", replacement: webSrc("modules/communications/hooks/useNotificationSound") },
      { find: "@/hooks/usePayrollRecords", replacement: webSrc("modules/payroll/hooks/usePayrollRecords") },
      { find: "@/hooks/usePayrollRules", replacement: webSrc("modules/payroll/hooks/usePayrollRules") },
      { find: "@/hooks/usePermission", replacement: webSrc("modules/auth/hooks/usePermission") },
      { find: "@/hooks/usePlatformAdmin", replacement: webSrc("modules/admin/hooks/usePlatformAdmin") },
      { find: "@/hooks/useQuickBooks", replacement: webSrc("modules/billing/hooks/useQuickBooks") },
      { find: "@/hooks/useQuickBooksSync", replacement: webSrc("modules/billing/hooks/useQuickBooksSync") },
      { find: "@/hooks/useRingCentral", replacement: webSrc("modules/communications/hooks/useRingCentral") },
      { find: "@/hooks/useRingCentralSync", replacement: webSrc("modules/communications/hooks/useRingCentralSync") },
      { find: "@/hooks/useSendEmail", replacement: webSrc("modules/communications/hooks/useSendEmail") },
      { find: "@/hooks/useSendNotificationSMS", replacement: webSrc("modules/communications/hooks/useSendNotificationSMS") },
      { find: "@/hooks/useStaff", replacement: webSrc("modules/settings/hooks/useStaff") },
      { find: "@/hooks/useSupportTickets", replacement: webSrc("modules/support/hooks/useSupportTickets") },
      { find: "@/hooks/useTransactionRules", replacement: webSrc("modules/transactions/hooks/useTransactionRules") },
      { find: "@/hooks/useTransactions", replacement: webSrc("modules/transactions/hooks/useTransactions") },
      { find: "@/hooks/use-toast", replacement: webSrc("shared/hooks/use-toast") },
      { find: "@/contexts", replacement: webSrc("shared/contexts") },
      { find: "@/integrations", replacement: webSrc("shared/integrations") },
      { find: "@/lib", replacement: webSrc("shared/lib") },
      { find: "@/stores", replacement: webSrc("shared/stores") },
      { find: "@", replacement: webSrc() },
    ],
  },
});
