import { useMemo, useState } from "react";
import { BrowserRouter, Link, useLocation } from "react-router-dom";
import { Bell, ChevronRight, Menu, Search, X } from "lucide-react";
import { allNavigationItems, navigationGroups } from "./navigation";
import { MaidFlowRoutes } from "./MaidFlowRoutes";

const placeholderCopy: Record<string, { eyebrow: string; title: string; description: string }> = {
  "/": { eyebrow: "Foundation preview", title: "Maid Flow", description: "The new frontend foundation is active. Functional areas are rebuilt one at a time on top of this system." },
  "/operations/schedule": { eyebrow: "Operations", title: "Schedule", description: "Planning and execution of scheduled cleaning services in one operational workspace." },
  "/communications/inbox": { eyebrow: "Communications", title: "Inbox", description: "Customer and team conversations with delivery-aware messaging workflows." },
  "/finance/invoices": { eyebrow: "Finance", title: "Invoices", description: "Professional billing workflows, statuses and customer balances." },
  "/finance/payments": { eyebrow: "Finance", title: "Payments", description: "Payment records and reconciliation views independent from invoices." },
  "/finance/transactions": { eyebrow: "Finance", title: "Transactions", description: "Operational financial activity with clear categories and traceable origins." },
  "/finance/payroll": { eyebrow: "Finance", title: "Payroll", description: "Payroll runs, service allocations, adjustments and employee statements." },
  "/reports": { eyebrow: "Insights", title: "Reports", description: "Defined operational and financial metrics without artificial benchmark scoring." },
  "/settings": { eyebrow: "Administration", title: "Settings", description: "Company, team, services, notifications, automations and integration settings." },
  "/support": { eyebrow: "Help", title: "Support", description: "Product support and ticket workflows." },
  "/platform": { eyebrow: "Platform", title: "Platform administration", description: "Separate SaaS administration for companies, support and audit activity." },
};
function MaidFlowMark(){return <div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-md border border-white/10 bg-white/[0.06] text-[11px] font-semibold text-white">MF</div><div><p className="text-sm font-semibold text-white">Maid Flow</p><p className="text-[11px] text-slate-400">Operations workspace</p></div></div>}
function Sidebar({mobile,onNavigate}:{mobile?:boolean;onNavigate?:()=>void}){const location=useLocation();return <aside className={mobile?"flex h-full w-full flex-col bg-[hsl(var(--sidebar-background))]":"hidden h-screen w-[248px] shrink-0 flex-col bg-[hsl(var(--sidebar-background))] lg:flex"}><div className="flex h-16 items-center border-b border-white/[0.07] px-4"><MaidFlowMark/></div><nav className="scrollbar-thin flex-1 overflow-y-auto px-2 py-3" aria-label="Primary navigation">{navigationGroups.map((group,index)=><div key={group.label??`group-${index}`} className={index===0?"":"mt-5"}>{group.label&&<p className="mb-1.5 px-2 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{group.label}</p>}<div className="space-y-0.5">{group.items.map((item)=>{const active=item.path==="/"?location.pathname==="/":location.pathname.startsWith(item.path);const Icon=item.icon;return <Link key={item.path} to={item.path} onClick={onNavigate} className={`group flex h-9 items-center gap-2.5 rounded-md px-2.5 text-[13px] ${active?"bg-white/[0.09] font-medium text-white":"text-slate-300 hover:bg-white/[0.055] hover:text-white"}`}><Icon className={`h-[15px] w-[15px] ${active?"text-emerald-300":"text-slate-500"}`} strokeWidth={1.8}/><span>{item.label}</span></Link>})}</div></div>)}</nav><div className="border-t border-white/[0.07] p-3"><div className="flex items-center gap-2.5 px-2 py-2"><div className="grid h-7 w-7 place-items-center rounded-full bg-slate-700 text-[10px] font-semibold text-slate-100">AM</div><div><p className="text-xs font-medium text-slate-100">Admin preview</p><p className="text-[10px] text-slate-500">Frontend persona</p></div></div></div></aside>}
function PagePlaceholder(){const location=useLocation();const content=placeholderCopy[location.pathname]??placeholderCopy["/"];const current=allNavigationItems.find((item)=>location.pathname===item.path||(item.path!=="/"&&location.pathname.startsWith(item.path)));return <main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8 lg:py-7"><div className="mx-auto w-full max-w-[1500px]"><div className="mb-6 flex items-center gap-1.5 text-[11px] text-muted-foreground"><span>Maid Flow</span><ChevronRight className="h-3 w-3"/><span>{current?.label??"Foundation"}</span></div><header className="border-b border-border pb-5"><p className="mb-1.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-primary">{content.eyebrow}</p><h1 className="text-[29px] font-semibold tracking-[-0.035em]">{content.title}</h1><p className="mt-1.5 text-[13px] text-muted-foreground">{content.description}</p></header></div></main>}
function ApplicationFrame(){const[mobileOpen,setMobileOpen]=useState(false);const location=useLocation();const activeLabel=useMemo(()=>allNavigationItems.find((item)=>location.pathname===item.path||(item.path!=="/"&&location.pathname.startsWith(item.path)))?.label??"Maid Flow",[location.pathname]);return <div className="flex min-h-screen bg-background text-foreground"><Sidebar/>{mobileOpen&&<div className="fixed inset-0 z-50 lg:hidden"><button type="button" aria-label="Close navigation" className="absolute inset-0 bg-slate-950/45" onClick={()=>setMobileOpen(false)}/><div className="relative h-full w-[280px] max-w-[86vw]"><button type="button" aria-label="Close navigation" className="absolute right-3 top-3 z-10 grid h-8 w-8 place-items-center text-slate-400" onClick={()=>setMobileOpen(false)}><X className="h-4 w-4"/></button><Sidebar mobile onNavigate={()=>setMobileOpen(false)}/></div></div>}<div className="flex min-w-0 flex-1 flex-col"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-border bg-background/95 px-4 sm:px-6 lg:px-8"><button type="button" aria-label="Open navigation" className="mr-3 grid h-8 w-8 place-items-center rounded-md border border-border bg-card lg:hidden" onClick={()=>setMobileOpen(true)}><Menu className="h-4 w-4"/></button><div className="flex-1 text-[13px] font-medium">{activeLabel}</div><button type="button" aria-label="Search" className="hidden h-8 items-center gap-2 rounded-md border border-border bg-card px-2.5 text-xs text-muted-foreground sm:flex"><Search className="h-3.5 w-3.5"/>Search</button><button type="button" aria-label="Notifications" className="ml-1.5 grid h-8 w-8 place-items-center text-muted-foreground"><Bell className="h-[15px] w-[15px]"/></button></header><MaidFlowRoutes fallback={<PagePlaceholder/>}/></div></div>}
export function FoundationApp(){const baseUrl=import.meta.env.BASE_URL.replace(/\/$/,"");return <BrowserRouter basename={baseUrl||undefined}><ApplicationFrame/></BrowserRouter>}
