import { useMemo, useState } from "react";
import { BrowserRouter, Link, useLocation } from "react-router-dom";
import { ArrowLeft, ChevronRight, Menu, ShieldCheck, X } from "lucide-react";
import { allNavigationItems, navigationGroups } from "./navigation";
import { MaidFlowRoutes } from "./MaidFlowRoutes";
import { PublicLeadCapturePage } from "./PublicLeadCapturePage";

const placeholderCopy: Record<string, { eyebrow: string; title: string; description: string }> = {
  "/": { eyebrow: "Foundation", title: "Maid Flow", description: "The new frontend foundation is active." },
};
function MaidFlowMark(){return <div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-md border border-white/10 bg-white/[0.06] text-[11px] font-semibold text-white">MF</div><div><p className="text-sm font-semibold text-white">Maid Flow</p><p className="text-[11px] text-slate-400">Operations workspace</p></div></div>}
function Sidebar({mobile,onNavigate}:{mobile?:boolean;onNavigate?:()=>void}){const location=useLocation();return <aside className={mobile?"flex h-full w-full flex-col bg-[hsl(var(--sidebar-background))]":"hidden h-screen w-[248px] shrink-0 flex-col bg-[hsl(var(--sidebar-background))] lg:flex"}><div className="flex h-16 items-center border-b border-white/[0.07] px-4"><MaidFlowMark/></div><nav className="scrollbar-thin flex-1 overflow-y-auto px-2 py-3" aria-label="Primary navigation">{navigationGroups.map((group,index)=><div key={group.label??`group-${index}`} className={index===0?"":"mt-5"}>{group.label&&<p className="mb-1.5 px-2 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500">{group.label}</p>}<div className="space-y-0.5">{group.items.map((item)=>{const active=item.path==="/"?location.pathname==="/":location.pathname.startsWith(item.path);const Icon=item.icon;return <Link key={item.path} to={item.path} onClick={onNavigate} className={`group flex h-9 items-center gap-2.5 rounded-md px-2.5 text-[13px] ${active?"bg-white/[0.09] font-medium text-white":"text-slate-300 hover:bg-white/[0.055] hover:text-white"}`}><Icon className={`h-[15px] w-[15px] ${active?"text-emerald-300":"text-slate-500"}`} strokeWidth={1.8}/><span>{item.label}</span></Link>})}</div></div>)}</nav><div className="border-t border-white/[0.07] p-3"><Link to="/platform" onClick={onNavigate} className="flex items-center gap-2.5 rounded-md px-2 py-2 text-slate-300 hover:bg-white/[0.055] hover:text-white"><div className="grid h-7 w-7 place-items-center rounded-md bg-slate-800"><ShieldCheck className="h-3.5 w-3.5"/></div><div><p className="text-xs font-medium">Platform admin</p><p className="text-[10px] text-slate-500">Switch context</p></div></Link></div></aside>}
function PagePlaceholder(){const location=useLocation();const content=placeholderCopy[location.pathname]??placeholderCopy["/"];const current=allNavigationItems.find((item)=>location.pathname===item.path||(item.path!=="/"&&location.pathname.startsWith(item.path)));return <main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8 lg:py-7"><div className="mx-auto w-full max-w-[1500px]"><div className="mb-6 flex items-center gap-1.5 text-[11px] text-muted-foreground"><span>Maid Flow</span><ChevronRight className="h-3 w-3"/><span>{current?.label??"Foundation"}</span></div><header className="border-b border-border pb-5"><p className="mb-1.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-primary">{content.eyebrow}</p><h1 className="text-[29px] font-semibold tracking-[-0.035em]">{content.title}</h1><p className="mt-1.5 text-[13px] text-muted-foreground">{content.description}</p></header></div></main>}
function ApplicationFrame(){const[mobileOpen,setMobileOpen]=useState(false);const location=useLocation();const activeLabel=useMemo(()=>allNavigationItems.find((item)=>location.pathname===item.path||(item.path!=="/"&&location.pathname.startsWith(item.path)))?.label??"Maid Flow",[location.pathname]);if(location.pathname.startsWith("/request-service"))return <PublicLeadCapturePage/>;if(location.pathname.startsWith("/platform"))return <div className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 sm:px-6 lg:px-8"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-md border border-border bg-card text-[11px] font-semibold">MF</div><div><p className="text-xs font-semibold">Maid Flow · Platform administration</p><p className="text-[10px] text-muted-foreground">Separate administrative context</p></div></div><Link to="/" className="inline-flex h-8 items-center gap-1.5 rounded-md border border-border bg-card px-3 text-[11px] font-semibold hover:bg-muted"><ArrowLeft className="h-3.5 w-3.5"/>Back to workspace</Link></header><MaidFlowRoutes fallback={<PagePlaceholder/>}/></div>;return <div className="flex min-h-screen bg-background text-foreground"><Sidebar/>{mobileOpen&&<div className="fixed inset-0 z-50 lg:hidden"><button type="button" aria-label="Close navigation" className="absolute inset-0 bg-slate-950/45" onClick={()=>setMobileOpen(false)}/><div className="relative h-full w-[280px] max-w-[86vw]"><button type="button" aria-label="Close navigation" className="absolute right-3 top-3 z-10 grid h-8 w-8 place-items-center text-slate-400" onClick={()=>setMobileOpen(false)}><X className="h-4 w-4"/></button><Sidebar mobile onNavigate={()=>setMobileOpen(false)}/></div></div>}<div className="flex min-w-0 flex-1 flex-col"><header className="sticky top-0 z-30 flex h-16 items-center border-b border-border bg-background/95 px-4 sm:px-6 lg:px-8"><button type="button" aria-label="Open navigation" className="mr-3 grid h-8 w-8 place-items-center rounded-md border border-border bg-card lg:hidden" onClick={()=>setMobileOpen(true)}><Menu className="h-4 w-4"/></button><div className="flex-1 text-[13px] font-medium">{activeLabel}</div></header><MaidFlowRoutes fallback={<PagePlaceholder/>}/></div></div>}
export function FoundationApp(){const baseUrl=import.meta.env.BASE_URL.replace(/\/$/,"");return <BrowserRouter basename={baseUrl||undefined}><ApplicationFrame/></BrowserRouter>}
