import { ChevronRight, ShieldCheck } from "lucide-react";
import { rolePermissions, type MaidFlowPermission, type MaidFlowRole } from "../../../../../packages/domain/access";

const roles:readonly MaidFlowRole[]=["admin","office_manager","cleaning_manager","virtual_assistant","cleaner","driver","platform_admin"];
const permissionGroups:readonly {label:string;permissions:readonly MaidFlowPermission[]}[]=[
  {label:"CRM",permissions:["crm.read","crm.manage"]},
  {label:"Schedule",permissions:["schedule.read","schedule.manage","schedule.execute"]},
  {label:"Communications",permissions:["communications.read","communications.send"]},
  {label:"Finance",permissions:["finance.read","finance.manage","payroll.read","payroll.manage"]},
  {label:"Administration",permissions:["team.manage","settings.manage","platform.manage"]},
];
const label=(value:string)=>value.replaceAll("_"," ").replaceAll("."," · ");

export function SecuritySettingsPage(){return <main className="min-w-0 flex-1 px-4 py-5 sm:px-6 lg:px-8 lg:py-7"><div className="mx-auto w-full max-w-[1250px]"><div className="mb-6 flex items-center gap-1.5 text-[11px] text-muted-foreground"><span>Maid Flow</span><ChevronRight className="h-3 w-3"/><span>Settings</span><ChevronRight className="h-3 w-3"/><span className="text-foreground/80">Security</span></div><header className="border-b border-border pb-5"><p className="mb-1.5 text-[10px] font-semibold uppercase tracking-[0.13em] text-primary">Settings</p><h1 className="text-[26px] font-semibold tracking-[-0.035em] sm:text-[29px]">Security & access</h1><p className="mt-1.5 max-w-2xl text-[13px] text-muted-foreground">Canonical frontend permission model for UX validation. Real authorization will belong to the future backend.</p></header><section className="pt-5"><div className="mb-4 flex items-start gap-3 rounded-md border border-border bg-card p-4"><ShieldCheck className="mt-0.5 h-4 w-4 text-primary"/><div><h2 className="text-xs font-semibold">Frontend permission preview</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">This matrix determines which experiences should be visible to each persona during frontend development. It is not a security boundary.</p></div></div><div className="overflow-x-auto rounded-md border border-border bg-card"><table className="min-w-[1050px] w-full text-left text-[11px]"><thead className="border-b border-border bg-muted/45"><tr><th className="sticky left-0 bg-muted/45 px-4 py-2.5">Permission</th>{roles.map((role)=><th key={role} className="px-3 py-2.5 text-center capitalize">{label(role)}</th>)}</tr></thead><tbody className="divide-y divide-border">{permissionGroups.flatMap((group)=>[{kind:"group" as const,label:group.label},...group.permissions.map((permission)=>({kind:"permission" as const,label:permission}))]).map((row,index)=>row.kind==="group"?<tr key={`${row.label}-${index}`} className="bg-muted/20"><td colSpan={roles.length+1} className="px-4 py-2 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{row.label}</td></tr>:<tr key={row.label}><td className="sticky left-0 bg-card px-4 py-2.5 font-medium">{label(row.label)}</td>{roles.map((role)=><td key={role} className="px-3 py-2.5 text-center"><span className={`inline-block h-2 w-2 rounded-full ${rolePermissions[role].includes(row.label)?"bg-emerald-500":"bg-muted"}`}><span className="sr-only">{rolePermissions[role].includes(row.label)?"Allowed":"Not allowed"}</span></span></td>)}</tr>)}</tbody></table></div></section></div></main>}
